version: 0.2

phases:
  install:
    commands:
      - echo installing node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      # install yarn?
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      # build
      - echo building...
      - npm build
artifacts:
  files:
    - "**/*"
    discard-paths: no
    base-directory: build